### ISSUE TITLE
Scan error message when entering incorrect passport info

### ISSUE THREAD

**Issue by YaroShkvorets** [ZeroPass/flutter-port-app#1]
Entered wrong passport number, got this error after scanning:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/29608734/158600503-832c784f-fc3c-4cf9-9fda-0eb8e295c49e.png">

Would be nice if the error message was more descriptive asking the user to verify their passport data.

**Comment by smlu** [comment]
Should be fixed with commit c39c910599cc067a830083a0749bf6bf83008f13 now.
